name: Auto Update CCTV Snapshot

on:
  schedule:
    # Menggunakan sistem cron untuk berjalan secara berkala (Contoh: Setiap 15 minit)
    # GitHub Actions paling laju boleh berjalan sekitar 5 hingga 15 minit sekali demi menjaga kestabilan pelayan.
    - cron: '*/15 * * * *'
  workflow_dispatch: # Butang ini membolehkan anda klik "Run" secara manual pada bila-bila masa

jobs:
  update-snapshot:
    runs-on: ubuntu-latest

    steps:
    - name: Semak fail repositori
      uses: actions/checkout@v3

    - name: Pasang FFmpeg (Alat penangkap gambar)
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Tangkap gambar dari M3U8 Cloudfront
      run: |
        ffmpeg -i "https://d2idp3hzkhjpih.cloudfront.net/out/v1/4b85d9c2bf97413eb0c9fd875599b837/index_3.m3u8" -vframes 1 -q:v 2 index.jpg

    - name: Muat naik gambar index.jpg ke GitHub Pages
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "action@github.com"
        git add index.jpg
        git commit -m "Auto-update CCTV snapshot [Cloudfront]" || exit 0
        git push
        
